#!/usr/bin/env python3
"""
Calculate the Variational Predictability (VP) score.

This script reads image pairs generated by `gen_pairs.py` from
`<EXP>/vp_pairs/` and trains a simple classifier ("Reconstructor") to
predict which support direction generated each pair. It follows the
paper's VP protocol:

- Split pairs: 10% train / 90% test (random).
- Model: small CNN from `lib.reconstructor` (default: LeNet variant).
- Optimizer: Adam.
- LR: 0.005.
- Epochs: 300.
- Batch size: 32.
- Metric: test classification accuracy (%), reported as VP score.

Outputs
-------
- `<EXP>/vp_pairs/vp_metrics.json` with train/test accuracy.
- Optionally saves the trained reconstructor checkpoint.

Example
-------
python calculate_vp.py \
  --exp experiments/wip/SNGAN_AnimeFaces-LeNet-K15-D10__20250919_041423 \
  --reconstructor-type LeNet --epochs 300 --batch-size 32 --lr 0.005

Notes
-----
- Images are stored as concatenated pairs (left=x0, right=xT) in BGR JPEG.
  We split down the middle, convert to RGB, and normalize to [-1, 1].
- If the number of labels in `labels.npy` does not match the number of
  image files, we take the minimum count and warn.
- `dim_index` (number of classes K) is inferred from `labels.npy`.
  `dim_time` is read from `<EXP>/args.json` when available; otherwise
  defaults to 10.
"""

from __future__ import annotations

import argparse
import json
import os
import os.path as osp
import random
from dataclasses import dataclass
from typing import Tuple

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

# Use the project's reconstructor implementation
from lib.reconstructor import Reconstructor  # noqa: F401


# ------------------------------
# Utilities
# ------------------------------

def seed_everything(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def choose_device(use_cuda: bool, use_mps: bool) -> torch.device:
        # Device selection
    cuda_available = torch.cuda.is_available()
    mps_available = hasattr(torch.backends, 'mps') and torch.backends.mps.is_available()
    use_cuda = use_cuda and cuda_available
    use_mps = use_mps and mps_available
    
    device = torch.device('cuda' if use_cuda else ('mps' if use_mps else 'cpu'))

    # Set default tensor type for CUDA only (no MPS default tensor type exists)
    if use_cuda:
        torch.set_default_device(torch.device('cuda'))
    elif use_mps:
        torch.set_default_device(torch.device('mps'))
        torch.set_default_dtype(torch.float32)
    else:
        torch.set_default_device(torch.device('cpu'))

    return device, use_cuda, use_mps


@dataclass
class VPConfig:
    exp_dir: str
    pairs_dir: str
    epochs: int = 300
    batch_size: int = 32
    lr: float = 5e-3
    train_frac: float = 0.10
    num_workers: int = 4
    seed: int = 0
    reconstructor_type: str = "LeNet"  # or "ResNet"
    resize: int | None = None           # if set, resize shorter side to this; otherwise use native
    save_ckpt: bool = False


# ------------------------------
# Dataset
# ------------------------------

class PairDataset(Dataset):
    def __init__(self, img_files, labels, resize: int | None = None):
        assert len(img_files) == labels.shape[0]
        self.img_files = img_files
        self.labels = labels
        self.resize = resize

    def __len__(self) -> int:
        return len(self.img_files)

    def __getitem__(self, idx: int):
        path = self.img_files[idx]
        lab = self.labels[idx]
        y = int(np.argmax(lab))

        img = cv2.imread(path, cv2.IMREAD_COLOR)
        if img is None:
            raise FileNotFoundError(f"Failed to read image: {path}")
        # BGR -> RGB
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        h, w, _ = img.shape
        mid = w // 2
        x1 = img[:, :mid]
        x2 = img[:, mid:]

        if self.resize is not None:
            # Keep aspect 1:1; both halves are same size
            x1 = cv2.resize(x1, (self.resize, self.resize), interpolation=cv2.INTER_AREA)
            x2 = cv2.resize(x2, (self.resize, self.resize), interpolation=cv2.INTER_AREA)

        # to float32 in [-1, 1]
        x1 = (x1.astype(np.float32) / 127.5) - 1.0
        x2 = (x2.astype(np.float32) / 127.5) - 1.0

        # HWC -> CHW
        x1 = torch.from_numpy(x1).permute(2, 0, 1)
        x2 = torch.from_numpy(x2).permute(2, 0, 1)
        y = torch.tensor(y, dtype=torch.long)
        return x1, x2, y


# ------------------------------
# Train / Eval
# ------------------------------

def train_one_epoch(model: nn.Module, loader: DataLoader, opt: torch.optim.Optimizer, device: torch.device) -> Tuple[float, float]:
    model.train()
    total, correct, total_loss = 0, 0, 0.0
    ce = nn.CrossEntropyLoss()

    for x1, x2, y in loader:
        x1 = x1.to(device, non_blocking=True)
        x2 = x2.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)

        logits, _ = model(x1, x2)
        loss = ce(logits, y)

        opt.zero_grad(set_to_none=True)
        loss.backward()
        opt.step()

        total += y.size(0)
        total_loss += float(loss.detach()) * y.size(0)
        pred = torch.argmax(logits.detach(), dim=1)
        correct += int((pred == y).sum())

    avg_loss = total_loss / max(1, total)
    acc = 100.0 * correct / max(1, total)
    return avg_loss, acc


def evaluate(model: nn.Module, loader: DataLoader, device: torch.device) -> Tuple[float, float]:
    model.eval()
    ce = nn.CrossEntropyLoss()
    total, correct, total_loss = 0, 0, 0.0

    with torch.no_grad():
        for x1, x2, y in loader:
            x1 = x1.to(device, non_blocking=True)
            x2 = x2.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)

            logits, _ = model(x1, x2)
            loss = ce(logits, y)

            total += y.size(0)
            total_loss += float(loss) * y.size(0)
            pred = torch.argmax(logits, dim=1)
            correct += int((pred == y).sum())

    avg_loss = total_loss / max(1, total)
    acc = 100.0 * correct / max(1, total)
    return avg_loss, acc


# ------------------------------
# Main
# ------------------------------

def main():
    ap = argparse.ArgumentParser(description="Compute VP score from generated image pairs")
    ap.add_argument("--exp", required=True, type=str, help="Path to experiment dir (parent of models/)")
    ap.add_argument("--pairs-dir", type=str, default=None, help="Override: directory containing pair_*.jpg and labels.npy")
    ap.add_argument("--epochs", type=int, default=300)
    ap.add_argument("--batch-size", type=int, default=32)
    ap.add_argument("--lr", type=float, default=5e-3)
    ap.add_argument("--train-frac", type=float, default=0.10)
    ap.add_argument("--num-workers", type=int, default=4)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--reconstructor-type", type=str, default="LeNet", choices=["LeNet", "ResNet"])
    ap.add_argument("--resize", type=int, default=None, help="If set, resize each half to this square side (e.g., 64 or 128)")
    # Device flags (mirrors your other scripts)
    ap.add_argument("--cuda", dest="cuda", action="store_true")
    ap.add_argument("--no-cuda", dest="cuda", action="store_false")
    ap.add_argument("--mps", dest="mps", action="store_true")
    ap.add_argument("--no-mps", dest="mps", action="store_false")
    ap.add_argument("--save-ckpt", action="store_true")
    ap.set_defaults(cuda=False, mps=True)

    args = ap.parse_args()

    seed_everything(args.seed)

    # Dataloaders
    device, use_cuda, use_mps = choose_device(args.cuda, args.mps)
    pin = device.type in {"cuda"}
    

    # Resolve paths
    exp_dir = args.exp
    if not osp.isdir(exp_dir):
        raise NotADirectoryError(f"Invalid experiment directory: {exp_dir}")

    pairs_dir = args.pairs_dir or osp.join(exp_dir, "vp_pairs")
    if not osp.isdir(pairs_dir):
        raise NotADirectoryError(f"Pairs directory not found: {pairs_dir}")

    # Load labels
    labels_path = osp.join(pairs_dir, "labels.npy")
    if not osp.isfile(labels_path):
        raise FileNotFoundError(f"Missing labels.npy in {pairs_dir}")
    labels = np.load(labels_path)
    if labels.ndim != 2:
        raise ValueError(f"labels.npy should be 2D (N x K), got shape {labels.shape}")

    # Gather image files
    img_files = sorted(
        [osp.join(pairs_dir, f) for f in os.listdir(pairs_dir) if f.lower().endswith(".jpg") and f.startswith("pair_")]
    )

    if len(img_files) == 0:
        raise RuntimeError(f"No pair_*.jpg files found in {pairs_dir}")

    # Robustness to potential mismatch (e.g., some scripts saved B instead of B*K per batch)
    n_images = len(img_files)
    n_labels = labels.shape[0]
    if n_images != n_labels:
        print(
            f"[WARN] Number of images ({n_images}) != number of labels ({n_labels}). "
            f"Proceeding with min count = {min(n_images, n_labels)}."
        )
        n = min(n_images, n_labels)
        img_files = img_files[:n]
        labels = labels[:n]
        print(labels[:10])

    K = labels.shape[1]  # number of support directions (classes)

    # Load optional args.json to get T (num_support_timesteps)
    args_json = osp.join(exp_dir, "args.json")
    T = 10
    if osp.isfile(args_json):
        try:
            with open(args_json, "r") as f:
                a = json.load(f)
            T = int(a.get("num_support_timesteps", T))
        except Exception as e:
            print(f"[WARN] Failed to parse {args_json}: {e}. Using T={T}.")

    # Split train/test
    indices = np.arange(len(img_files))
    rng = np.random.RandomState(args.seed)
    rng.shuffle(indices)

    n_train = max(1, int(len(indices) * args.train_frac))
    train_idx = indices[:n_train]
    test_idx = indices[n_train:]

    def subset(arr, idx):
        return [arr[i] for i in idx]

    train_ds = PairDataset(subset(img_files, train_idx), labels[train_idx], resize=args.resize)
    test_ds = PairDataset(subset(img_files, test_idx), labels[test_idx], resize=args.resize)


    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=0 if use_mps else args.num_workers,
        # pin_memory=pin,
        drop_last=False,
        generator=torch.Generator(device=device),
    )
    test_loader = DataLoader(
        test_ds,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=0 if use_mps else args.num_workers,
        # pin_memory=pin,
        drop_last=False,
        generator=torch.Generator(device=device),
    )

    # Model
    model = Reconstructor(
        reconstructor_type=args.reconstructor_type,
        dim_index=K,
        dim_time=T,
        channels=3,
    ).to(device)
    # Optimizer (paper only specifies LR; use Adam for stability)
    opt = torch.optim.Adam(model.parameters(), lr=args.lr)

    # Train
    best_test_acc = 0.0
    for epoch in range(1, args.epochs + 1):
        tr_loss, tr_acc = train_one_epoch(model, train_loader, opt, device)
        te_loss, te_acc = evaluate(model, test_loader, device)
        best_test_acc = max(best_test_acc, te_acc)
        if epoch % 10 == 0 or epoch == 1 or epoch == args.epochs:
            print(
                f"Epoch {epoch:3d}/{args.epochs} | "
                f"train loss {tr_loss:.4f} acc {tr_acc:6.2f}% | "
                f"test loss {te_loss:.4f} acc {te_acc:6.2f}%"
            )

    # Final evaluation
    te_loss, te_acc = evaluate(model, test_loader, device)
    print(f"\nVP Score (test accuracy): {te_acc:.2f}%  (best: {best_test_acc:.2f}%)")

    # Save metrics & optional checkpoint
    metrics = {
        "vp_score_test_acc_percent": round(float(te_acc), 4),
        "best_test_acc_percent": round(float(best_test_acc), 4),
        "train_frac": args.train_frac,
        "epochs": args.epochs,
        "batch_size": args.batch_size,
        "lr": args.lr,
        "K": int(K),
        "T": int(T),
        "reconstructor_type": args.reconstructor_type,
        "device": device.type,
        "num_pairs_total": int(len(img_files) + (0)),
        "num_pairs_train": int(len(train_ds)),
        "num_pairs_test": int(len(test_ds)),
    }
    out_metrics = osp.join(pairs_dir, "vp_metrics.json")
    with open(out_metrics, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"Saved metrics to {out_metrics}")

    if args.save_ckpt:
        ckpt_path = osp.join(pairs_dir, f"reconstructor_{args.reconstructor_type.lower()}.pth")
        torch.save({
            "state_dict": model.state_dict(),
            "K": K,
            "T": T,
            "type": args.reconstructor_type,
            "metrics": metrics,
        }, ckpt_path)
        print(f"Saved checkpoint to {ckpt_path}")


if __name__ == "__main__":
    main()
